# 2D matrix addition using numpy


In [2]:
#importing Libraries
import numpy as np

In [5]:
A1=np.random.rand(3,4)

In [6]:
A1

array([[0.13223162, 0.47211677, 0.95711848, 0.26943079],
       [0.44555417, 0.60589212, 0.68715495, 0.85947041],
       [0.26487805, 0.80039189, 0.95510434, 0.08882355]])

In [7]:
A2=np.random.rand(3,4)

In [8]:
A2

array([[0.33771603, 0.21687864, 0.69785597, 0.5403734 ],
       [0.62547437, 0.33026344, 0.46977897, 0.76738734],
       [0.21562254, 0.50897799, 0.28354707, 0.54964922]])

In [17]:
B=A1+A2

In [14]:
B
%timeit (B)

42.7 ns ± 4.59 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [15]:
(r,c)=A1.shape

In [18]:
#addittion using for loops
for i in range(r):
    for j in range(c):
        B[i,j]=A1[i,j]+A2[i,j]


In [20]:
%timeit (B)

48.1 ns ± 9.9 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [22]:
B=np.zeros((r,c))
for i in range(r):
    for j in range(c):
        B[i,j]=A1[i,j]+A2[i,j]


In [23]:
print (B)

[[0.46994765 0.68899542 1.65497445 0.80980419]
 [1.07102854 0.93615556 1.15693391 1.62685774]
 [0.48050059 1.30936988 1.23865141 0.63847277]]


In [24]:
%timeit (B)

44.6 ns ± 3.07 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [25]:
A1

array([[0.13223162, 0.47211677, 0.95711848, 0.26943079],
       [0.44555417, 0.60589212, 0.68715495, 0.85947041],
       [0.26487805, 0.80039189, 0.95510434, 0.08882355]])

In [26]:
A2

array([[0.33771603, 0.21687864, 0.69785597, 0.5403734 ],
       [0.62547437, 0.33026344, 0.46977897, 0.76738734],
       [0.21562254, 0.50897799, 0.28354707, 0.54964922]])

In [27]:
A3

array([[0.46994765, 0.68899542, 1.65497445, 0.80980419],
       [1.07102854, 0.93615556, 1.15693391, 1.62685774],
       [0.48050059, 1.30936988, 1.23865141, 0.63847277]])

# 3D matrix addition using Numpy

In [32]:
A3=np.random.rand(1,5,3)

In [33]:
A3

array([[[0.26441232, 0.81684312, 0.89631916],
        [0.51662096, 0.01276918, 0.96847503],
        [0.45249649, 0.69117302, 0.07373529],
        [0.96907087, 0.68445796, 0.00170494],
        [0.27889233, 0.59088341, 0.90620314]]])

In [38]:
A4=np.random.rand(1,5,3)

In [39]:
A4

array([[[0.55018633, 0.299844  , 0.65258111],
        [0.57706321, 0.96656204, 0.34749893],
        [0.23353284, 0.37157368, 0.13133117],
        [0.63877132, 0.61130949, 0.48298451],
        [0.98500193, 0.48524762, 0.51146826]]])

In [40]:
A3+A4

array([[[0.81459865, 1.11668712, 1.54890026],
        [1.09368417, 0.97933122, 1.31597396],
        [0.68602933, 1.0627467 , 0.20506646],
        [1.60784219, 1.29576745, 0.48468944],
        [1.26389427, 1.07613103, 1.4176714 ]]])

In [41]:
(e,r,c)=A3.shape

In [43]:
C=np.zeros((e,r,c))

In [44]:
C

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
for i in range(e):
    for j in range(r):
        for k in range(c):
            C[i,j,k]=A3[i,j,k]+A4[i,j,k]

In [47]:
C

array([[[0.81459865, 1.11668712, 1.54890026],
        [1.09368417, 0.97933122, 1.31597396],
        [0.68602933, 1.0627467 , 0.20506646],
        [1.60784219, 1.29576745, 0.48468944],
        [1.26389427, 1.07613103, 1.4176714 ]]])

In [48]:
%timeit (C)

45 ns ± 7.06 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
