# Matrix_multiplication using For loops

In [1]:
#importing libraries
import numpy as np

In [2]:
#create a random Matrix
A=np.random.rand(3,4)

In [3]:
A

array([[0.36403968, 0.67754482, 0.42473767, 0.40855858],
       [0.12109996, 0.42944063, 0.17656256, 0.30061851],
       [0.3839006 , 0.3421855 , 0.22754318, 0.52127467]])

In [4]:
#to know length of A
len(A[0])

4

In [5]:
#to know the rows,columns of Ath matrix
(r,c)=A.shape

In [6]:
#to create the random matrix B
B=np.random.rand(4,3)

In [7]:
B

array([[0.162023  , 0.48173959, 0.28270244],
       [0.26624723, 0.15511618, 0.89163913],
       [0.57786761, 0.85568881, 0.94091332],
       [0.9278599 , 0.85911518, 0.12532917]])

In [8]:
#assigning the number of rows and columns to Bth matrix
(m,n)=B.shape

In [9]:
#matrix multiplication using numpy
np.dot(A,B)

array([[0.8639045 , 0.99491265, 1.15788602],
       [0.51492001, 0.53430037, 0.62094765],
       [0.76846636, 0.88055976, 0.69306494]])

In [10]:
#creating the output matxix of (no of rows in first matrix(r) ,no of columns in second matrix)
C=np.zeros((r,n))

In [11]:
C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#program to generate Multiplication of matrix

if c==m:
    for i in range(r):
        #print('i is',i)
        for j in range(n):
            #print('j is',j)
            for k in range(m):
                #print('k is',k)
                #print('c[i,j] is',C[i,j])
                C[i,j]+=A[i,k]*B[k,j]
                #print('c[i,j] is',C[i,j])
                #print(C)
else:
    print('Not possiple')
    


# Matrix Transpose

In [13]:
A=np.random.rand(3,4)

In [14]:
A

array([[0.92499371, 0.66830297, 0.52764074, 0.24598842],
       [0.01623211, 0.67046054, 0.54998133, 0.45153256],
       [0.64601014, 0.22962366, 0.25051597, 0.8271813 ]])

In [15]:
(r,c)=A.shape

In [16]:
transpose=[]

In [17]:
transpose

[]

In [18]:
for i in range(c):
    L=[]
    for j in A:
        L.append(j[i])
    transpose.append(L)

In [19]:
transpose

[[0.9249937112913674, 0.016232108034113124, 0.6460101429700231],
 [0.668302971420127, 0.6704605362460195, 0.2296236618398232],
 [0.5276407357030797, 0.549981328007784, 0.25051596652248187],
 [0.24598842252796949, 0.45153255691089755, 0.8271812982182292]]

In [20]:
#using Numpy arrays Transpose
M=np.zeros((c,r))

In [21]:
M

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
for i in range(c):
    for j in range(r):
        M[i,j]=A[j,i]

In [23]:
M

array([[0.92499371, 0.01623211, 0.64601014],
       [0.66830297, 0.67046054, 0.22962366],
       [0.52764074, 0.54998133, 0.25051597],
       [0.24598842, 0.45153256, 0.8271813 ]])

In [24]:
#using list comprehension method
transposed=[[row[i] for row in A] for i in range(c)]

In [25]:
transposed

[[0.9249937112913674, 0.016232108034113124, 0.6460101429700231],
 [0.668302971420127, 0.6704605362460195, 0.2296236618398232],
 [0.5276407357030797, 0.549981328007784, 0.25051596652248187],
 [0.24598842252796949, 0.45153255691089755, 0.8271812982182292]]