# hstack

In [1]:
#hstack is concataning the the arrays in to horizontal for this operation the rows in first matrix is equal to rows in second matrix otherwise it is not possible
import numpy as np

In [5]:
A=np.random.rand(3,4)

In [6]:
B=np.random.rand(2,3)

In [7]:
C=np.hstack((A,B)) #because rows are mismatching

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [8]:
B=np.random.rand(3,3)

In [11]:
print(A.shape)
print(B.shape)

(3, 4)
(3, 3)


In [12]:
C=np.hstack((A,B))

In [13]:
C

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143, 0.86649457,
        0.98032292, 0.10351916],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061, 0.09545676,
        0.39134291, 0.61549774],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 , 0.11868125,
        0.0680028 , 0.71284014]])

In [14]:
A

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 ]])

In [15]:
B

array([[0.86649457, 0.98032292, 0.10351916],
       [0.09545676, 0.39134291, 0.61549774],
       [0.11868125, 0.0680028 , 0.71284014]])

In [35]:
B=np.random.rand(2,4)

In [36]:
B

array([[0.62439751, 0.07005903, 0.84850831, 0.49569484],
       [0.1800542 , 0.91329109, 0.02117416, 0.13554732]])

In [19]:
C=np.hstack((A,B)) #hstack is not possible

ValueError: all the input array dimensions except for the concatenation axis must match exactly

# vstack

In [21]:
C=np.vstack((A,B))

In [22]:
C

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 ],
       [0.97881057, 0.12264268, 0.61559121, 0.88917785],
       [0.18786373, 0.85443444, 0.37644769, 0.51134119]])

In [23]:
A

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 ]])

In [38]:
B=np.random.rand(3,4)

In [39]:
B

array([[0.02271793, 0.52361768, 0.65405489, 0.01863213],
       [0.73497849, 0.02780494, 0.00494095, 0.4860456 ],
       [0.27543743, 0.41686371, 0.18961631, 0.71452199]])

In [29]:
C=np.stack((A,B))

In [30]:
C

array([[[0.09487953, 0.37484597, 0.1921135 , 0.32398143],
        [0.60240857, 0.03556396, 0.50268864, 0.02953061],
        [0.15387141, 0.46044792, 0.33726717, 0.0872333 ]],

       [[0.60034346, 0.73697548, 0.38778057, 0.61840694],
        [0.44021391, 0.1345736 , 0.2334836 , 0.4598646 ],
        [0.04584415, 0.07812574, 0.0426587 , 0.93343592]]])

In [31]:
C.shape

(2, 3, 4)

In [33]:
np.concatenate((A,B),axis=0) #concatinate without stacks

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 ],
       [0.60034346, 0.73697548, 0.38778057, 0.61840694],
       [0.44021391, 0.1345736 , 0.2334836 , 0.4598646 ],
       [0.04584415, 0.07812574, 0.0426587 , 0.93343592]])

In [34]:
np.concatenate((A,B),axis=1)

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143, 0.60034346,
        0.73697548, 0.38778057, 0.61840694],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061, 0.44021391,
        0.1345736 , 0.2334836 , 0.4598646 ],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 , 0.04584415,
        0.07812574, 0.0426587 , 0.93343592]])

In [43]:
np.concatenate((A,B),axis=1)

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143, 0.02271793,
        0.52361768, 0.65405489, 0.01863213],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061, 0.73497849,
        0.02780494, 0.00494095, 0.4860456 ],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 , 0.27543743,
        0.41686371, 0.18961631, 0.71452199]])

In [41]:
np.concatenate((A,B))

array([[0.09487953, 0.37484597, 0.1921135 , 0.32398143],
       [0.60240857, 0.03556396, 0.50268864, 0.02953061],
       [0.15387141, 0.46044792, 0.33726717, 0.0872333 ],
       [0.02271793, 0.52361768, 0.65405489, 0.01863213],
       [0.73497849, 0.02780494, 0.00494095, 0.4860456 ],
       [0.27543743, 0.41686371, 0.18961631, 0.71452199]])

# stacks using 3D array

In [44]:
A=np.random.rand(5,3,2)
B=np.random.rand(5,1,2)

In [47]:
C=np.hstack((A,B))

In [48]:
C

array([[[0.23124548, 0.40609121],
        [0.63796165, 0.2959105 ],
        [0.21787461, 0.53844123],
        [0.78333587, 0.10845101]],

       [[0.3804634 , 0.55867137],
        [0.61301297, 0.85265589],
        [0.39528273, 0.38828823],
        [0.618928  , 0.44125036]],

       [[0.03805059, 0.41408165],
        [0.02743237, 0.11678411],
        [0.72932633, 0.86485792],
        [0.00722755, 0.06271598]],

       [[0.3056286 , 0.58279376],
        [0.9081977 , 0.94469551],
        [0.31044938, 0.2016267 ],
        [0.56820967, 0.69314186]],

       [[0.67095604, 0.00440383],
        [0.68697814, 0.95320539],
        [0.91354373, 0.84551324],
        [0.95028244, 0.95939515]]])

In [49]:
C.shape

(5, 4, 2)

In [50]:
A=np.random.rand(4,4,2)
B=np.random.rand(5,1,2)

In [51]:
C=np.hstack((A,B)) #not possible because length is not matching h stack

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [52]:
A=np.random.rand(4,2,2)
B=np.random.rand(5,2,2)

In [53]:
C=np.vstack((A,B))

In [54]:
C

array([[[0.06535597, 0.63067676],
        [0.40120768, 0.1199108 ]],

       [[0.95069177, 0.52914097],
        [0.28500301, 0.20521552]],

       [[0.83682493, 0.85914777],
        [0.33181102, 0.10736054]],

       [[0.78652566, 0.72071479],
        [0.70788265, 0.42309865]],

       [[0.81944637, 0.85062546],
        [0.3723811 , 0.34734551]],

       [[0.98155344, 0.84207694],
        [0.97810325, 0.95501091]],

       [[0.29590124, 0.5150725 ],
        [0.50194767, 0.30388293]],

       [[0.18787179, 0.71319547],
        [0.39498187, 0.52306569]],

       [[0.08715097, 0.33696452],
        [0.76298255, 0.65922613]]])

In [55]:
C.shape

(9, 2, 2)

In [58]:
A=np.random.rand(5,4,2)
B=np.random.rand(5,4,2)

In [59]:
C=np.stack((A,B))

In [60]:
C

array([[[[0.254525  , 0.64399947],
         [0.80335167, 0.61635665],
         [0.08314896, 0.48275618],
         [0.80434723, 0.18315225]],

        [[0.44913315, 0.17534095],
         [0.31293247, 0.09640816],
         [0.15030643, 0.16070838],
         [0.42182283, 0.85594607]],

        [[0.12446859, 0.44568911],
         [0.53290418, 0.76770437],
         [0.54329766, 0.03163408],
         [0.89064633, 0.54490675]],

        [[0.28600451, 0.97816322],
         [0.96126533, 0.54961383],
         [0.18581606, 0.75284081],
         [0.10106923, 0.62888228]],

        [[0.91405136, 0.12301179],
         [0.866619  , 0.84696902],
         [0.0230442 , 0.32257604],
         [0.36545312, 0.69395578]]],


       [[[0.35216615, 0.47209495],
         [0.40410371, 0.85127318],
         [0.37679781, 0.12101305],
         [0.75086659, 0.64042809]],

        [[0.99202436, 0.57568243],
         [0.26404805, 0.60886762],
         [0.95889463, 0.76704933],
         [0.62944014, 0.99169763]],

    

In [61]:
C.shape

(2, 5, 4, 2)